# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='fullname',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
