# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toader', '0002_people_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='username',
        ),
    ]
