# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toader', '0006_auto_20171001_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='fullname',
        ),
    ]
